/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { MediaEngineStore, VoiceActions } from "@equicord/types/webpack/common";

import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@equicord/types/plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("read if cute :3");
VesktopLogger.log(`Testktop v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "testcord_testktop_settings",
    title: "Testktop Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "TestktopSettings",
    label: "Testktop Settings",
    element: SettingsUi,
    className: "vc-testktop-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());
VesktopNative.voice.onToggleVAD(() => {
    const voiceActions = VoiceActions as any;
    const mediaEngineStore = MediaEngineStore as any;

    const currentMode = mediaEngineStore?.getMode?.();
    const nextMode = currentMode === "PUSH_TO_TALK" ? "VOICE_ACTIVITY" : "PUSH_TO_TALK";

    if (typeof voiceActions?.setMode === "function") {
        voiceActions.setMode(nextMode);
        return;
    }
});

// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
